# Train/val/test sets
path: yolo_finetune/labelImg_data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/test
test: images/test 

# Classes
names:
  0: knee

# Download script/URL (optional)
download: https://github.com/ultralytics/assets/releases/download/v0.0.0/coco8.zip