seed: 42
device: cuda

task:
  classes: ["Tibia_L","Fibula_L","Femur_L","Pelvis","Femur_R","Tibia_R","Fibula_R"]
  num_class: 7
  threshold: 0.5

data:
  dataset: ["gnu"]

  gnu:
    root: /mnt/d/hyebin/xgait/dataset/GNU
    split_json: /mnt/d/hyebin/xgait/dataset/GNU_json/GNU_split.json
    train_key: TRAIN_SET
    test_key: TEST_SET

  snu:
    root: /mnt/d/hyebin/xgait/dataset/SNU
    split_json: /mnt/d/hyebin/xgait/dataset/GNU_json/GNU_split.json
    train_key: TRAIN_SET
    test_key: TEST_SET

  input:
    size: 512
    to_grayscale: true
    normalize: true

test:
  ckpt: /mnt/d/hyebin/xgait/boneseg/output/gnu_attnunet_512/ckpt/final.pth
  save_pred: true
  out_pth: /mnt/d/hyebin/xgait/align_metric/output
  overlay_alpha: 0.35

visualize:
  thickness: 20
  radius: 30